---
- name: Apply configuration to Juniper box
  hosts:
    - home-lab
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Load set, compare diff, commit check and then commit changes with comment
      juniper_junos_config:
        timeout: 100
        port: 22
        commit: true
        diff: true
        config_mode: private
        check: true
        lines:
          - "delete system services telnet"
        load: 'set'
        format: 'set'
        comment: 'Removing TELNET - JVB'
        ignore_warning: 'statement not found'
