---
- name: Examples of juniper_junos_command
  hosts: home-lab
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: Get uptime
      juniper_junos_rpc:
        rpc: get-system-uptime-information
        port: 22
      register: response

    - name: Print the command output
      debug:
        var: response.stdout
